spring.application.name=Api Gateway
server.port=8080

gateway.routes.inventory=${GATEWAY_INVENTORY_URL:http://localhost:8083}
gateway.routes.order=${GATEWAY_ORDER_URL:http://localhost:8081/order}
gateway.routes.payment=${GATEWAY_PAYMENT_URL:http://localhost:8082}
gateway.routes.notification=${GATEWAY_NOTIFICATION_URL:http://localhost:8084}

