package com.works.apigateway.controller;

import jakarta.servlet.http.HttpServletRequest;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.util.StreamUtils;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.util.UriComponentsBuilder;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

@RestController
@RequiredArgsConstructor
public class GatewayProxyController {

    private static final String INVENTORY_PREFIX = "/inventory";
    private static final String ORDER_PREFIX = "/order";
    private static final String PAYMENT_PREFIX = "/payment";
    private static final String NOTIFICATION_PREFIX = "/notification";

    private final RestTemplate restTemplate = new RestTemplate();

    @Value("${gateway.routes.inventory}")
    private String inventoryBaseUrl;

    @Value("${gateway.routes.order}")
    private String orderBaseUrl;

    @Value("${gateway.routes.payment}")
    private String paymentBaseUrl;

    @Value("${gateway.routes.notification}")
    private String notificationBaseUrl;

    @RequestMapping({
            INVENTORY_PREFIX,
            INVENTORY_PREFIX + "/**",
            ORDER_PREFIX,
            ORDER_PREFIX + "/**",
            PAYMENT_PREFIX,
            PAYMENT_PREFIX + "/**",
            NOTIFICATION_PREFIX,
            NOTIFICATION_PREFIX + "/**"
    })
    public ResponseEntity<byte[]> proxy(HttpServletRequest request, @RequestBody(required = false) byte[] body) throws IOException {
        String requestPath = request.getRequestURI();
        String baseUrl = resolveBaseUrl(requestPath);
        String forwardedPath = resolveForwardedPath(requestPath);

        String targetUrl = UriComponentsBuilder.fromUriString(baseUrl)
                .path(forwardedPath)
                .query(request.getQueryString())
                .build(true)
                .toUriString();

        HttpHeaders headers = new HttpHeaders();
        copyHeaders(request, headers);

        HttpMethod method = HttpMethod.valueOf(request.getMethod());
        byte[] payload = body != null ? body : StreamUtils.copyToByteArray(request.getInputStream());
        HttpEntity<byte[]> entity = new HttpEntity<>(payload, headers);

        ResponseEntity<byte[]> response = restTemplate.exchange(targetUrl, method, entity, byte[].class);

        HttpHeaders responseHeaders = new HttpHeaders();
        responseHeaders.putAll(response.getHeaders());
        return ResponseEntity.status(response.getStatusCode()).headers(responseHeaders).body(response.getBody());
    }

    private String resolveBaseUrl(String requestPath) {
        if (requestPath.startsWith(INVENTORY_PREFIX)) {
            return inventoryBaseUrl;
        }
        if (requestPath.startsWith(ORDER_PREFIX)) {
            return orderBaseUrl;
        }
        if (requestPath.startsWith(PAYMENT_PREFIX)) {
            return paymentBaseUrl;
        }
        if (requestPath.startsWith(NOTIFICATION_PREFIX)) {
            return notificationBaseUrl;
        }
        throw new IllegalArgumentException("Unsupported route path: " + requestPath);
    }

    private String resolveForwardedPath(String requestPath) {
        if (requestPath.startsWith(INVENTORY_PREFIX)) {
            return stripPrefixOrRoot(requestPath, INVENTORY_PREFIX);
        }
        if (requestPath.startsWith(ORDER_PREFIX)) {
            return stripPrefixOrRoot(requestPath, ORDER_PREFIX);
        }
        if (requestPath.startsWith(PAYMENT_PREFIX)) {
            return stripPrefixOrRoot(requestPath, PAYMENT_PREFIX);
        }
        if (requestPath.startsWith(NOTIFICATION_PREFIX)) {
            return stripPrefixOrRoot(requestPath, NOTIFICATION_PREFIX);
        }
        return "/";
    }

    private String stripPrefixOrRoot(String requestPath, String prefix) {
        String stripped = requestPath.substring(prefix.length());
        return stripped.isEmpty() ? "/" : stripped;
    }

    private void copyHeaders(HttpServletRequest request, HttpHeaders headers) {
        var names = request.getHeaderNames();
        while (names.hasMoreElements()) {
            String name = names.nextElement();
            // Host and Content-Length are generated by the HTTP client.
            if ("host".equalsIgnoreCase(name) || "content-length".equalsIgnoreCase(name)) {
                continue;
            }
            var values = request.getHeaders(name);
            while (values.hasMoreElements()) {
                headers.add(name, values.nextElement());
            }
        }
        headers.add("X-Gateway", "ApiGateway");
        headers.add("X-Gateway-Charset", StandardCharsets.UTF_8.name());
    }
}

